id: P010737
initial_creation_type: ocr
created_at: 30/03/2020
last_modified_at: 2021-12-20 10:22:13.438501
source_metadata:
  id: bdr:W23212
  title: ཐུགས་རྗེ་ཆེན་པོ་ངན་སོང་ཀུན་སྐྱོབས
  author: ''
  volumes:
    ae20da764b2b46a8b95476626d4e0b1d:
      image_group_id: I1974
      title: ''
      volume_number: 1
      total_pages: 486
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
