id: IE8BF99C0
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T23:16:04+00:00'
last_modified: '2022-06-08T17:09:50.553666+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W23212
  title: ཐུགས་རྗེ་ཆེན་པོ་ངན་སོང་ཀུན་སྐྱོབས
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    42FF:
      image_group_id: I1974
      title: ''
      total_pages: 486
      order: 1
      base_file: 42FF.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
